package com.myspace.process.inquiry.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerFactoringInquiry implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomerFactoringInquiry() {
    }




}